--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/ItsToxicGG/PartyEngine
build-by-default: true
branches:
- main
projects:
  PartyEngine:
    path: ""
    libs:
      - src: EasyUI
        version: ^1.0.2    
...
